POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title":"How to Fix TypeError: Cannot read Property 'push' of Undefined in JavaScript",
    "author":"Joel Olawanle",
    "url":"https://www.freecodecamp.org/news/fix-typeerror-cannot-read-property-push-of-undefined-in-javascript/",
    "likes":22
}